config/routes.rb
Rails.application.routes.draw do
  
  root "main#index"
  get "login" => "main#login"
  
  get 'users' => "users#index"
  get 'users/show' => "users#show"
  get 'teachers' => "teachers#index"
  get 'teachers/new_pupil' => "teachers#new_pupil"
  get 'teachers/pupils'  => "teachers#pupils"
  get 'teachers/show_pupil'  => "teachers#show_pupil"

  get 'stories/index'  => "stories#index"
  get 'stories/new'  => "stories#new"
  get 'stories/show_story'  => "stories#show_story"
  
  devise_for :users
  devise_for :teachers

  

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/main_controller.rb
 class MainController < ApplicationController

 def index
  	render "main/index"
 end
 def login
 	render "main/login"
 end
end

app/controllers/pupils_controller.rb
 class PupilsController < ApplicationController

	 def index
	  	render "users/index"
	 end

	def show
		render "users/show"
	end

end

app/controllers/stories_controller.rb
 class StoriesController < ApplicationController

	 def index
	  	render "stories/index"
	 end

	def new
		render "stories/new"
	end

	def show
		render "stories/show_story"
	end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

	def index
		render "teachers/index"
	end

	def new_pupil
		render "teachers/new_pupil"
	end

	def pupils
		render "teachers/pupils"
	end

	def show_pupil
		render "teachers/show_pupil"
	end

end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  #The path used after sign up.
  def after_sign_up_path_for(resource)
   '/teachers/'
  end

  # The path used after sign up for inactive accounts.
 def after_inactive_sign_up_path_for(resource)
     '/teachers/'
  end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/user/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
 class UsersController < ApplicationController

	 def index
	  	render "users/index"
	 end

	def show
		render "users/show"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top navbar-custom" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">APRENDIS</a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="active"><a href="/teachers">Home</a></li>

			</ul>

				<ul class="nav navbar-nav navbar-right">
							 		<% if teacher_signed_in? %>
				<li>
					<%= link_to('Logout', destroy_teacher_session_path, :method => :delete) %>        
				</li>
				<% else %>
				<li>
					<li><%= link_to('Login as teacher', new_teacher_session_path)  %> </li>
				</li>
				<% end %>
				</ul>


		
		</div>
		<!--/.nav-collapse -->
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>H4gBackend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">

  <link rel="stylesheet" href="http://cdn.jsdelivr.net/animatecss/2.1.0/animate.min.css">
 <style>
        body {
            padding-top: 100px;
                background-image: url("/assets/ninos.jpeg");
    background-repeat:no-repeat;
    background-size: cover;
    background-attachment: fixed;
        }

        .starter-template {
            padding: 40px 15px;
            text-align: center;
        }

    </style>

</head>


<body>

<%= render partial: "layouts/header" %>


<%= yield %>


</body>
</html>

app/views/main/index.html.erb
<div class="container-flux">
	
	<div id="inicioBox">

		<div class="col-xs-12" style="padding-top: 15vh"></div>

		<div class="col-xs-12" style="background-color: rgba(240,240,240,0.3); height: 100%"></div>

		<div class="col-xs-12 col-sm-8 col-sm-offset-2 animated bounceInLeft  " style="position: absolute">
			<div class="row">
				<div class="col-xs-12 col-sm-4">
					<img src="/assets/nexus.png" alt="/assets/images/nexus.png" class="img img-responsive">

				</div>

				<div class="col-xs-12 col-sm-8">
					<div style="height: 8vh"></div>
					<h1 style="font-weight: bold;">APRENDIZAJE SOCIAL</h1>
					<h2 style="font-weight: lighter">La primera plataforma game center que facilita el Aprendisaje Social de personas con discapacidad intelectual</h2>
					
				</div>

			</div>

		</div>
		
	</div>
</div>

app/views/stories/index.html.erb
<div class="back-lado"></div>


<div class="container-fluid">
	<div class="col-xs-12 col-xs-offset-1 well-custom well-recto">
		<div class="row">
			<div class="col-xs-8">
				<h1>Historias</h1>
			</div>
			<div class="col-xs-4">
				<a href="/stories/new"><button class="btn glyOpt">
					<span class="glyphicon glyphicon-plus "></span> Nueva historia
				</button>
				</a>

			</div> 

		</div>

	</div>


		
	<div class="col-xs-10 col-xs-offset-1 well well-custom well-recto">
		<br>
			<div class="col-xs-12 col-sm-4 col-md-3">
			
			<a href="/stories/show_story"><div class="card text-center">
				<div style="background-color: #ABA"><img class="card-img-top card-img-propio img img-responsive img-square" src="/assets/metro.jpg" alt="Card image cap"></div>
				<div class="card-block">
					<p pupilCardText ><span class="glyphicon glyphicon-star pupilCardText"></span><span class="glyphicon glyphicon-star pupilCardText"></span><span class="glyphicon glyphicon-star pupilCardText"></span><span class="glyphicon glyphicon-star-empty pupilCardText"></span><span class="glyphicon glyphicon-star-empty pupilCardText"></span></p>
					<p class="pupilCardText"><big>OrientaMetro</big></p>
					<p class="card-text pupilCardText "><small class="text-muted">Orientación</small></p>
					<p class="card-text pupilCardText">Historia sobre retos de orientación en la red de Metro de Madrid</p>
					<a href="#" class="card-link">Card link</a>
					<a href="#" class="card-link">Another link</a>

				</div>
			</div>
			</a>
		</div>

			<div class="col-xs-12 col-sm-4 col-md-3">
			<div class="card text-center">
				<div style="background-color: #ABA"><img class="card-img-top card-img-propio img img-responsive img-square" src="/assets/citya.jpg" alt="Card image cap"></div>
				<div class="card-block">
					<p><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star-empty"></span><span class="glyphicon glyphicon-star-empty"></span></p>
					<p><big>OrientaMetro</big></p>
					<p class="card-text"><small class="text-muted">Orientación</small></p>
					<p class="card-text">Historia sobre retos de orientación en la red de Metro de Madrid</p>
					<a href="#" class="card-link">Card link</a>
					<a href="#" class="card-link">Another link</a>

				</div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-4 col-md-3">
			<div class="card text-center">
				<div style="background-color: #ABA"><img class="card-img-top card-img-propio img img-responsive img-square" src="/assets/social.png" alt="Card image cap"></div>
				<div class="card-block">
					<p><big>Bigger text</big></p>
					<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
					<p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
					<a href="#" class="card-link">Card link</a>
					<a href="#" class="card-link">Another link</a>

				</div>
			</div>
		</div>
				<div class="col-xs-12 col-sm-4 col-md-3">
			<div class="card text-center">
				<div style="background-color: #ABA"><img class="card-img-top card-img-propio img img-responsive img-square" src="/assets/social.png" alt="Card image cap"></div>
				<div class="card-block">
					<p><big>Bigger text</big></p>
					<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
					<p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
					<a href="#" class="card-link">Card link</a>
					<a href="#" class="card-link">Another link</a>

				</div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-4 col-md-3">
			<div class="card text-center">
				<div style="background-color: #ABA"><img class="card-img-top card-img-propio img img-responsive img-square" src="/assets/metro.jpg" alt="Card image cap"></div>
				<div class="card-block">
					<p><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star-empty"></span><span class="glyphicon glyphicon-star-empty"></span></p>
					<p><big>OrientaMetro</big></p>
					<p class="card-text"><small class="text-muted">Orientación</small></p>
					<p class="card-text">Historia sobre retos de orientación en la red de Metro de Madrid</p>
					<a href="#" class="card-link">Card link</a>
					<a href="#" class="card-link">Another link</a>

				</div>
			</div>
		</div>

			<div class="col-xs-12 col-sm-4 col-md-3">
			<div class="card text-center">
				<div style="background-color: #ABA"><img class="card-img-top card-img-propio img img-responsive img-square" src="/assets/citya.jpg" alt="Card image cap"></div>
				<div class="card-block">
					<p><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star-empty"></span><span class="glyphicon glyphicon-star-empty"></span></p>
					<p><big>OrientaMetro</big></p>
					<p class="card-text"><small class="text-muted">Orientación</small></p>
					<p class="card-text">Historia sobre retos de orientación en la red de Metro de Madrid</p>
					<a href="#" class="card-link">Card link</a>
					<a href="#" class="card-link">Another link</a>

				</div>
			</div>
		</div>

				


	</div>

</div>

app/views/stories/new.html.erb
<div class="back-lado"></div>


<div class="container-fluid">
	<div class="col-xs-12 col-xs-offset-1 well-custom well-recto">
		<div class="row">
			<div class="col-xs-8">
				<h1>NUEVA HISTORIA</h1>
			</div>
			<div class="col-xs-4">
				<a href="/stories/save"><button class="btn glyOpt">
					<span class="
					glyphicon glyphicon-ok"></span> Guardar
				</button>
			</a>

		</div> 

	</div>

</div>



<div class="col-xs-10 col-xs-offset-1 well well-custom well-recto">
	<div class="row">
		<div class="col-xs-12">
			<div class="row">
				<div class="col-xs-6">
					<div class="form-group">
						<span>
							<label for="name"><h2>Nombre historia:</h2>
								<input class="form-control" type="string" id="name"></label>
							</span>
						</div>
					</div>
					<div class="col-xs-6">
						<div class="form-group">
							<span><label for="dificulty"><h2>Dificultad:</h2>
								<select class="form-control" name="dificulty" id="dificulty">

									<option value="1">1</option>
									<option value="2">2	</option>
									<option value="3">3</option>
									<option value="4">4</option>
									<option value="5">5</option>

								</select>
							</div>
						</div>
					</div>

					<div class="col-xs-12">
						<div class="form-group">
							<label for="description">Descripción:</label>
							<textarea class="form-control" rows="3" id="description"></textarea>
						</div>
						<hr>
					</div>	



					<div class="col-xs-12 text-center">
						<h2>Añadir escenas:</h2>
						<div class="row">
							<div class="col-xs-10 col-xs-offset-1 well-custom">
								<div class="row">

								<div class="col-xs-4 col-sm-4 col-md-3">
										<div class="card text-center">
											<div><img class="card-img-top card-img-propio img img-square" src="/assets/metro.jpg" alt="Card image cap"></div>
											<div class="card-block">
												<p><big>Bigger text</big></p>
												<p class="card-text">Categoria</p>
												<div class="checkbox">
													<label><input type="checkbox" value="">Añadir</label>
												</div>
											</div>
										</div>
									</div>
									<div class="col-xs-4 col-sm-4 col-md-3">
										<div class="card text-center">
											<div><img class="card-img-top card-img-propio img img-square" src="/assets/rol.jpg" alt="Card image cap"></div>
											<div class="card-block">
												<p><big>Bigger text</big></p>
												<p class="card-text">Categoria</p>
												<div class="checkbox">
													<label><input type="checkbox" value="">Añadir</label>
												</div>
											</div>
										</div>
									</div>
									<div class="col-xs-4 col-sm-4 col-md-3">
										<div class="card text-center">
											<div><img class="card-img-top card-img-propio img img-square" src="/assets/metro.jpg" alt="Card image cap"></div>
											<div class="card-block">
												<p><big>Bigger text</big></p>
												<p class="card-text">Categoria</p>
												<div class="checkbox">
													<label><input type="checkbox" value="">Añadir</label>
												</div>
											</div>
										</div>
									</div>
									<div class="col-xs-4 col-sm-4 col-md-3">
										<div class="card text-center">
											<div><img class="card-img-top card-img-propio img img-square" src="/assets/citya.jpg" alt="Card image cap"></div>
											<div class="card-block">
												<p><big>Bigger text</big></p>
												<p class="card-text">Categoria</p>
												<div class="checkbox">
													<label><input type="checkbox" value="">Añadir</label>
												</div>
											</div>
										</div>
									</div>


								</div>

							</div>


						</div>






					</div>	
				</div>
			</div>

app/views/stories/show_story.html.erb
<div class="back-lado"></div>


<div class="container-fluid">
	<div class="col-xs-12 col-xs-offset-1 well-custom well-recto">
		<div class="row">
			<div class="col-xs-8">
				<h1>HISTORIA</h1>
			</div>
			<div class="col-xs-4">
				<a href="/stories/save"><button class="btn glyOpt">
					<span class="
					glyphicon glyphicon-pencil"></span> Editar
				</button>
			</a>
			<a href="/stories/save"><button class="btn glyOpt">
					<span class="
					glyphicon glyphicon-trash"></span> Borrar
				</button>
			</a>

		</div> 

	</div>

</div>



<div class="col-xs-10 col-xs-offset-1 well well-custom well-recto">
	<div class="row">
		<div class="col-xs-12">
			<div class="row">
				<div class="col-xs-6">
				<h1>OrientaMetro</h1>
					</div>
					<div class="col-xs-6">
							<span class="glyphicon glyphicon-star glyHis"></span>
							<span class="glyphicon glyphicon-star glyHis"></span>
							<span class="glyphicon glyphicon-star glyHis"></span>
							<span class="glyphicon glyphicon-star-empty glyHis"></span>
							<span class="glyphicon glyphicon-star-empty glyHis"></span>
						</div>
					</div>

					<div class="col-xs-12">
						<h3>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab natus, ullam rem sed, velit ipsa eveniet impedit officia nostrum quasi veniam? Odit, reiciendis eligendi officiis neque provident explicabo tenetur, rem hic saepe a laboriosam consequuntur, ipsum autem vitae repellendus.</h3>
						<hr>
					</div>	



					<div class="col-xs-12 text-center">
						<h2>Escenas:</h2>
						<div class="row">
							<div class="col-xs-10 col-xs-offset-1 well-custom">
								<div class="row">

									<div class="col-xs-4 col-sm-4 col-md-3">
										<div class="card text-center">
											<div><img class="card-img-top card-img-propio img img-square" src="/assets/metro.jpg" alt="Card image cap"></div>
											<div class="card-block">
												<p><big>Bigger text</big></p>
												<p class="card-text">Categoria</p>
											
											</div>
										</div>
									</div>
									<div class="col-xs-4 col-sm-4 col-md-3">
										<div class="card text-center">
											<div><img class="card-img-top card-img-propio img img-square" src="/assets/rol.jpg" alt="Card image cap"></div>
											<div class="card-block">
												<p><big>Bigger text</big></p>
												<p class="card-text">Categoria</p>
												
											</div>
										</div>
									</div>
									<div class="col-xs-4 col-sm-4 col-md-3">
										<div class="card text-center">
											<div><img class="card-img-top card-img-propio img img-square" src="/assets/metro.jpg" alt="Card image cap"></div>
											<div class="card-block">
												<p><big>Bigger text</big></p>
												<p class="card-text">Categoria</p>
												
											</div>
										</div>
									</div>
									<div class="col-xs-4 col-sm-4 col-md-3">
										<div class="card text-center">
											<div><img class="card-img-top card-img-propio img img-square" src="/assets/citya.jpg" alt="Card image cap"></div>
											<div class="card-block">
												<p><big>Bigger text</big></p>
												<p class="card-text">Categoria</p>
												
											</div>
										</div>
									</div>


								</div>

							</div>


						</div>






					</div>	
				</div>
			</div>

app/views/teachers/index.html.erb
<div class="container-fluid">
	<div class="col-xs-12 col-sm-8">

		<div class="row">
			<br>
			<div class="col-xs-12 col-sm-8 col-sm-offset-2">
				<h1>NOTIFICACIONES</h1>
			</div>

			<div class="col-xs-12 col-sm-9 animated bounceInLeft">
				<div class="well-custom well-notificacion">
					<div class="row">
						<div class="col-xs-8"><p>Juan Pasó el nivel 5 de comunicación</p></div>
						<div class="col-xs-4"><small> hace unos segundos</small></div>
					</div>
				</div>
			</div>
				<div class="col-xs-12 col-sm-10 animated bounceInLeft">
				<div class="well-custom well-notificacion">
					<div class="row">
						<div class="col-xs-8"><p>Patricia Cerro la aplicación</p></div>
						<div class="col-xs-4"><small> hace unos minutos</small></div>
					</div>
				</div>
			</div>
				<div class="col-xs-12 col-sm-8 animated bounceInLeft">
				<div class="well-custom well-notificacion">
					<div class="row">
						<div class="col-xs-10"><p><span class="
					glyphicon glyphicon-warning-sign" style="color:#F00;font-size: 4em">  </span> <span style="opacity: 0">sa</span>Patricia FALLÓ en el reto social sobre señuelos en Facebook<span style="opacity: 0">sa</span><span class="
					glyphicon glyphicon-warning-sign" style="color:#F00;font-size: 4em">  </span> </p></div>
						<div class="col-xs-2"><small> hace 15 minutos</small></div>
					</div>
				</div>
			</div>
				<div class="col-xs-12 col-sm-10 animated bounceInLeft">
				<div class="well-custom well-notificacion">
					<div class="col-xs-8"><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur, hic?</p></div>
						<div class="col-xs-4"><small> hace 30 minutos</small></div>
				</div>
			</div>
				<div class="col-xs-12 col-sm-8 animated bounceInLeft">
				<div class="well-custom well-notificacion">
					<div class="col-xs-8"><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p></div>
						<div class="col-xs-4"><small> hace 40 minutos</small></div>
				</div>
			</div>
			<div class="col-xs-12 col-sm-9 animated bounceInLeft">
				<div class="well-custom well-notificacion">
					<div class="col-xs-8"><p>Lorem ipsum dolor sit amet, </p></div>
						<div class="col-xs-4"><small> hace 1 hora</small></div>
				</div>
			</div>
				<div class="col-xs-12 col-sm-8 animated bounceInLeft">
				<div class="well-custom well-notificacion">
					<div class="col-xs-8"><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p></div>
						<div class="col-xs-4"><small> hace más de 1 hora</small></div>
				</div>
			</div>

	<div class="col-xs-12 col-sm-10 animated bounceInLeft">
				<div class="well-custom well-notificacion">
					<div class="col-xs-8"><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur, hic?</p></div>
						<div class="col-xs-4"><small> hace 2 horas</small></div>
			</div>
				<div class="col-xs-12 col-sm-8 animated bounceInLeft">
				<div class="well-custom well-notificacion">
					<div class="col-xs-8"><p>Lorem ipsum dolor sit amet, consectetur</p></div>
						<div class="col-xs-4"><small> hace 2 horas</small></div>
				</div>
			</div>
			<div class="col-xs-12 col-sm-9 animated bounceInLeft">
				<div class="well-custom well-notificacion">
					<div class="col-xs-8"><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p></div>
						<div class="col-xs-4"><small> hace 2 horas</small></div>
				</div>
			</div>
				<div class="col-xs-12 col-sm-8 animated bounceInLeft">
				<div class="well-custom well-notificacion">
					<div class="col-xs-8"><p>Lorem ipsum dolor sit amet, consectetur </p></div>
						<div class="col-xs-4"><small> hace 1 día</small></div>
				</div>
				</div>
					<div class="col-xs-12 col-sm-8 animated bounceInLeft">
				<div class="well-custom well-notificacion">
					<div class="col-xs-8"><p>Lorem ipsum dolor sit amet, consectetur </p></div>
						<div class="col-xs-4"><small> hace 1 día</small></div>
				</div>
				</div>
					<div class="col-xs-12 col-sm-8 animated bounceInLeft">
				<div class="well-custom well-notificacion">
					<div class="col-xs-8"><p>Lorem ipsum dolor sit amet, consectetur </p></div>
						<div class="col-xs-4"><small> hace 1 día</small></div>
				</div>
				</div>
			</div>


		</div>

	</div>
	<div class="col-sm-4 hid-mobile">
		<div class="row">
			<div class="col-xs-10 col-xs-offset-1 well-custom well-recto animated bounceInDown" >
				<h1>Menu</h1>
				<hr>
				<a href="/teachers/pupils">
						<button class="btn btn-Menu btn-block" value="sada">Alumnos</button>
				</a>
				<br>
					<a href="/teachers/new_pupil">
						<button class="btn btn-Menu btn-block" value="sada">Añadir Alumno</button>
				</a>
				<br>
					<a href="/stories/index">
						<button class="btn btn-Menu btn-block" value="sada">Historias</button>
				</a>
				<br>
					<a href="/stories/new">
						<button class="btn btn-Menu btn-block" value="sada">Crear historia</button>
				</a>
				<br>
								
			</div>
		</div>
	</div>


</div>






<div class="container">
	<div class="row">
	<br>


<div class="col-xs-12" id="PupilsList">
	<!--<div class="row">
		<a class="col-xs-6 col-sm-3 well-custom well-btn" href=""><span>a</span></a>

		<a class="col-xs-6 col-sm-3 well-custom well-btn" href=""><span>a</span></a>
		<a class="col-xs-6 col-sm-3 well-custom well-btn" href=""><span>a</span></a>

	</div>-->
</div>
</div>
</div>

app/views/users/index.html.erb
<h1>/user/index</h1>

app/views/users/show.html.erb
<h1>Show</h1>